config/routes.rb
Rails.application.routes.draw do

  resources :users
  get 'outer_links/upload'

  get 'home/manage'

  root 'home#index'
  get 'index/' => 'home#index'
  get 'work/' => 'home#work'
  get 'interest/' => 'home#interest'
  get 'questionaire/'=>'outer_links#questionaire'
  post 'upload/'=>'outer_links#questionaire'
  post 'questionaire/'=>'users#create'

  get '/index/:lang' => 'home#index'
  get '/work/:lang' => 'home#work'
  get '/interest/:lang' => 'home#interest'
  get '/questionaire/:lang' => 'outer_links#questionaire'
  post '/upload/:lang' => 'outer_links#questionaire'
  get '/:lang' => 'home#index'

end

app/models/link_lang.rb
class LinkLang < ActiveRecord::Base
end

app/models/publication.rb
class Publication < ActiveRecord::Base
end

app/models/reading.rb
class Reading < ActiveRecord::Base
end

app/models/self_intro.rb
class SelfIntro < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/work_info.rb
class WorkInfo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
	def uploadFile(file)
	    if !file.original_filename.empty?
	    @filename=getFileName(file.original_filename)
	    File.open("#{Rails.root}/public/files/#{@filename}", "wb") do |f|
	    f.write(file.read)
	    end
	    return @filename
	    end
	end

	def getFileName(filename)
	    if !filename.nil?
	    return filename
	    end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	include HomeHelper
  def index
  	if params[:lang]!=nil
  		switch_lang(params[:lang])
  		redirect_to(:back)
  	end
  end

  def work
    if params[:lang]!=nil
      switch_lang(params[:lang])
      redirect_to(:back)
    end
  end

  def interest
    if params[:lang]!=nil
      switch_lang(params[:lang])
      redirect_to(:back)
    end
  end
end

app/controllers/outer_links_controller.rb
class OuterLinksController < ApplicationController
	include HomeHelper
  def questionaire
  	if params[:lang]!=nil
  		switch_lang(params[:lang])
  		redirect_to(:back)
  	end
  end

   def upload
   	if params[:lang]!=nil
  		switch_lang(params[:lang])
  		redirect_to(:back)
  	end
	   unless request.get?
	   	if params[:file]!=nil
		   if filename=uploadFile(params[:file]['file'])
		   end
		  end
	   end
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      @user.s1=params[:user][:age]
      @user.s2=params[:user][:gender]
      @user.s3=params[:user][:disease]
      @user.s4a=params[:user][:heartrate_morning]
      @user.s4b=params[:user][:heartrate_noon]
      @user.s4c=params[:user][:heartrate_night]
      @user.s5a=params[:user][:temp_morning]
      @user.s5b=params[:user][:temp_noon]
      @user.s5c=params[:user][:temp_night]
      @user.s6a=params[:user][:resp_morning]
      @user.s6b=params[:user][:resp_noon]
      @user.s6c=params[:user][:resp_night]
      @user.s7a=params[:user][:bp_morning]
      @user.s7b=params[:user][:bp_noon]
      @user.s7c=params[:user][:bp_night]
      @user.s8a=params[:user][:spo2_morning]
      @user.s8b=params[:user][:spo2_noon]
      @user.s8c=params[:user][:spo2_night]
    
    respond_to do |format|
      if @user.save
        if params[:user][:file_video]!=''
          @user.s9=Rails.root.join('public', 'files', 'video_'+@user.id.to_s)
        end
        if params[:user][:file_audio]!=''
          @user.s10=Rails.root.join('public', 'files', 'audio_'+@user.id.to_s)
        end
        upload
        QuestionMailer.record_email(@user).deliver
        format.html { redirect_to questionaire_path, notice: 'Questionaire Completed! Thank you!' }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def upload
    uploaded_io = params[:user][:file_video]
    if uploaded_io!=nil
      File.open(Rails.root.join('public', 'files', 'video_'+@user.id.to_s), 'wb') do |file|
        file.write(uploaded_io.read)
      end
    end
    uploaded_io = params[:user][:file_audio]
    if uploaded_io!=nil
      File.open(Rails.root.join('public', 'files', 'audio_'+@user.id.to_s), 'wb') do |file|
        file.write(uploaded_io.read)
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:uid, :s1, :s2, :s3, :s4a, :s4b, :s4c, :s5a, :s5b, :s5c, :s6a, :s6b, :s6c, :s7a, :s7b, :s7c, :s8a, :s8b, :s8c, :s9, :s10)
    end
end

app/helpers/home_helper.rb
module HomeHelper
		def make_title(page_title="")
			base_title="Weicheng's Homepage"
			if page_title.empty?
				base_title
			else
				page_title+"|"+base_title
			end
		end

		$langUsed="English"
		@@name=nil
		@@university=nil
		@@email=nil
		@@phone=nil
		@@intro=nil
		@@link_home=nil
		@@link_work=nil
		@@link_interest=nil
		@@link_reading=nil
		@@link_publication=nil
		@@link_questionaire=nil

		def initializer()
			intromod=SelfIntro.where("lang='"+$langUsed.to_s+"'")[0]
			@@name=intromod.name
			@@university=intromod.university
			@@email=intromod.email
			@@phone=intromod.phone
			@@intro=intromod.intro
			@@link_home=LinkLang.where("lang='"+$langUsed.to_s+"' and types='home'")[0].link
			@@link_work=LinkLang.where("lang='"+$langUsed.to_s+"' and types='work'")[0].link
			@@link_interest=LinkLang.where("lang='"+$langUsed.to_s+"' and types='interest'")[0].link
			@@link_reading=LinkLang.where("lang='"+$langUsed.to_s+"' and types='reading'")[0].link
			@@link_publication=LinkLang.where("lang='"+$langUsed.to_s+"' and types='publication'")[0].link
			@@link_questionaire=LinkLang.where("lang='"+$langUsed.to_s+"' and types='questionaire'")[0].link
		end

		def get_name()
			if @@name==nil
				initializer()
			end
			@@name
		end

		def get_university()
			if @@university==nil
				initializer()
			end
			@@university
		end

		def get_email()
			if @@email==nil
				initializer()
			end
			@@email
		end

		def get_phone()
			if @@phone==nil
				initializer()
			end
			@@phone
		end

		def get_intro()
			if @@intro==nil
				initializer()
			end
			@@intro
		end

		def get_link_home()
			if @@link_home==nil
				initializer()
			end
			@@link_home
		end

		def get_link_work()
			if @@link_home==nil
				initializer()
			end
			@@link_work
		end

		def get_link_interest()
			if @@link_home==nil
				initializer()
			end
			@@link_interest
		end

		def get_link_reading()
			if @@link_home==nil
				initializer()
			end
			@@link_reading
		end

		def get_link_publication()
			if @@link_home==nil
				initializer()
			end
			@@link_publication
		end

		def get_link_questionaire()
			if @@link_home==nil
				initializer()
			end
			@@link_questionaire
		end

		def switch_lang(lang)
			$langUsed=lang
			@@name=nil
			@@link_home=nil
		end

		def appendUrl(url,lang)
			if url.end_with?('/')!=true
				url=url+'/'
			end
			url+lang
		end

		def show_works()
			@works=WorkInfo.where("lang='"+$langUsed+"'")
		end

		def show_readings()
			@readings=Reading.order("create_at")
		end

		def show_publications()
			@publications=Publication.all
		end
end

app/helpers/outer_links_helper.rb
module OuterLinksHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
end

app/views/home/index.html.erb
<% provide(:title, "Home") %>

<div id="full_name"><%= get_name() %></div>
<div id="contact">
	<ul id="contact_info">
		<li><%= get_university() %></li>
		<li><%= get_email() %></li>
		<li><%= get_phone() %></li>
	</ul>
</div>
<div id="profile">
	<%= raw get_intro() %> 
</div>

app/views/home/interest.html.erb
<% provide(:title,"Interest") %>

app/views/home/manage.html.erb
<h1>Home#manage</h1>
<p>Find me in app/views/home/manage.html.erb</p>

app/views/home/work.html.erb
<% provide(:title,"Work") %>
<div id='displays' ng-app='displayapp' ng-controller='display_controller' ng-init='disp_reading=false;disp_publication=false;disp_cred=false;disp_modify=false;disp_manage=false;'>
	<%= render 'layouts/work_updates' %>
		<div id='work_list'>
			<%= link_to 'Manage Codes', '', {'class'=>'credential','ng-click'=>'show_credential()'} %><br>
			<% show_works() %>
			<% @works.each { |r| %>
			<div class='work_block'>
				<p class='title'><%= r.name %></p>
				<p class='description'><%= r.description %></p>
				<%= link_to 'Codes',r.link %>
			</div>
			<% } %>
		</div>
</div>

app/views/layouts/_header.html.erb
<div id='language'>
	<nav id='lang_link'>
		<ul>
			<%= link_to 'English', appendUrl(request.url,'English'), :lang=>'English', :class=>'lang'%>
			<%= link_to '中文', appendUrl(request.url,'Chinese'), :lang=>'Chinese', :class=>'lang'%>
			<%= link_to '日本語', appendUrl(request.url,'Japanese'), :lang=>'Japanese', :class=>'lang'%>
		</ul>
	</nav>
</div>

app/views/layouts/_main_navigator.html.erb
			<nav id='interlink'>
				<ul>
					<li><%= link_to get_link_home(), index_path, :id=>'home_link'%></li>
					<li><%= link_to get_link_work(), work_path, :id=>'work_link'%></li>
					<li><%= link_to get_link_interest(), interest_path, :id=>'interest_link'%></li>
					<li><%= link_to get_link_questionaire(), questionaire_path, :id=>'questionaire_link'%></li>
				</ul>
			</nav>

app/views/layouts/_work_updates.html.erb
	<ul>
		<li> <%= link_to get_link_reading(),'', {'id'=>'show_reading','ng-model'=> 'disp_reading', 'ng-click'=>'reading_click();hide_credential()'}%> </li>
		<li> <%= link_to get_link_publication(),'', {'id'=>'show_publication','ng-click'=>'publication_click();hide_credential()','ng-model'=>'disp_publication'}%> </li>
	</ul>
	<div class='display' ng-show='disp_reading' ng-animate="'animate'">
		<%= link_to 'close', '', {'class'=>'disp_close','ng-click'=>'close_click()'} %>
		<%= link_to 'manage', '', {'class'=>'credential','ng-click'=>'close_click();show_credential()'} %>
		<table class='disp_list'>
			<% show_readings() %>
			<% @readings.each { |r| %>
				<tr class='table_line'>
					<td class='cell'><%= r.author %></td> <td class='cell'><%= r.title %></td>
				</tr>
			<% } %>
		</table>
	</div>
	<div class='display' ng-show='disp_publication' ng-animate="'animate'">
		<%= link_to 'close', '', {'class'=>'disp_close','ng-click'=>'close_click()'} %>
		<%= link_to 'manage', '', {'class'=>'credential','ng-click'=>'close_click();show_credential()'} %>
		<table class='disp_list'>
			<% show_publications() %>
			<% @publications.each { |r| %>
				<tr class='table_line'>
					<td class='cell'><%= r.author %></td> <td class='cell'><%= r.title %></td><td class='cell'><%= r.time %></td>
				</tr>
			<% } %>
		</table>
	</div>
	<div class='cred' ng-show='disp_cred' ng-animate="'animate'">
		<center>
			Password: <input type='text' id='pwd' ng-model='pwd'><br>
			<button class='btn_pwd' ng-click='hide_credential();show_manage();'>Submit</button>
			<button class='btn_pwd' ng-click='hide_credential();'>Cancel</button>
		</center>
	</div>
	<div class='display' ng-show='disp_manage' ng-animate="'animate'">
		<%= link_to 'close', '', {'class'=>'disp_close','ng-click'=>'hide_manage()'} %>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title id='title'><%= make_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-animate.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-route.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-resource.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
	<center>
	<div id='page'>
		<div id='header'>
			<%= render 'layouts/header' %>
		</div>
		<div id='mainframe'>
			<div id='navigator'>
				<%= render 'layouts/main_navigator' %>
			</div>
			<div id='frame'>
				<canvas width="1920" height="1080" id='load_cover'>
				</canvas>
				<%= yield %>
			</div>
		</div>
	</div>
	</center>
</body>
</html>

app/views/outer_links/questionaire.html.erb
<% provide(:title, "Questionaire") %>
<div id='mainframe'>
	<div class='selection'>
		<%= form_for(:user) do |f| %>
		  <li><%= f.label(:s1, "1. What is your age?") %></li>
		  <li><%= f.radio_button(:age, "0-7") %>
		  <%= f.label(:age_1, "0-7") %></li>
		  <li><%= f.radio_button(:age, "8-13") %>
		  <%= f.label(:age_2, "8-13") %></li>
		  <li><%= f.radio_button(:age, "14-17") %>
		  <%= f.label(:age_3, "14-17") %></li>
		  <li><%= f.radio_button(:age, "18-24") %>
		  <%= f.label(:age_4, "18-24") %></li>
		  <li><%= f.radio_button(:age, "25-30") %>
		  <%= f.label(:age_5, "25-30") %></li>
		  <li><%= f.radio_button(:age, "31-40") %>
		  <%= f.label(:age_6, "31-40") %></li>
		  <li><%= f.radio_button(:age, "41-44") %>
		  <%= f.label(:age_7, "41-44") %></li>
		  <li><%= f.radio_button(:age, "45-54") %>
		  <%= f.label(:age_8, "45-54") %></li>
		  <li><%= f.radio_button(:age, "55-64") %>
		  <%= f.label(:age_9, "55-64") %></li>
		  <li><%= f.radio_button(:age, "65-74") %>
		  <%= f.label(:age_10, "65-74") %></li>
		  <li><%= f.radio_button(:age, "75 or older") %>
		  <%= f.label(:age_11, "75 or older") %></li>
		
		  <li><%= f.label(:s2, "2. What is your physical gender?") %></li>
		  <li><%= f.radio_button(:gender, "Male") %>
		  <%= f.label(:gender_1, "Male") %></li>
		  <li><%= f.radio_button(:gender, "Female") %>
		  <%= f.label(:gender_2, "Female") %></li>
		  <li><%= f.radio_button(:gender, "Unknown") %>
		  <%= f.label(:gender_3, "Prefer not to tell") %></li>
		
		  <li><%= f.label(:s3, "3. Do you have any illness?") %></li>
		  <li><%= f.radio_button(:disease, "No") %>
		  <%= f.label(:disease_1, "Not at all") %></li>
		  <li><%= f.radio_button(:disease, "Heart") %>
		  <%= f.label(:disease_2, "Heart related disease") %></li>
		  <li><%= f.radio_button(:disease, "Liver") %>
		  <%= f.label(:disease_3, "Liver related disease") %></li>
		  <li><%= f.radio_button(:disease, "Stomach") %>
		  <%= f.label(:disease_4, "Stomach related disease") %></li>
		  <li><%= f.radio_button(:disease, "Kidney") %>
		  <%= f.label(:disease_5, "Kidney related disease") %></li>
		  <li><%= f.radio_button(:disease, "Lung") %>
		  <%= f.label(:disease_6, "Lung related disease") %></li>
		
		  <%= f.label(:s4, "4. What's your heart rate(x/min) in the morning(8am-11am), during the day(11am-5pm), and in the evening(5pm-12am), respectively?") %>
		  <li><%= f.label(:heartrate_1, "Morning") %>
		  <%= f.text_field :heartrate_morning %></li>
		  <li><%= f.label(:heartrate_2, "Noon") %>
		  <%= f.text_field :heartrate_noon %></li>
		  <li><%= f.label(:heartrate_3, "Night") %>
		  <%= f.text_field :heartrate_night %></li>
		
		  <%= f.label(:s5, "5. What's your body temperature(Celcius) in the morning(8am-11am), during the day(11am-5pm), and in the evening(5pm-12am), respectively?") %>
		  <li><%= f.label(:temp_1, "Morning") %>
		  <%= f.text_field(:temp_morning) %></li>
		  <li><%= f.label(:temp_2, "Noon") %>
		  <%= f.text_field(:temp_noon) %></li>
		  <li><%= f.label(:temp_3, "Night") %>
		  <%= f.text_field(:temp_night) %></li>
		
		  <%= f.label(:s6, "6. What's your respiration rate(x/min) in the morning(8am-11am), during the day(11am-5pm), and in the evening(5pm-12am), respectively?") %>
		  <li><%= f.label(:resp_1, "Morning") %>
		  <%= f.text_field(:resp_morning) %></li>
		  <li><%= f.label(:resp_2, "Noon") %>
		  <%= f.text_field(:resp_noon) %></li>
		  <li><%= f.label(:resp_3, "Night") %>
		  <%= f.text_field(:resp_night) %></li>
		
		  <%= f.label(:s7, "7. What's your blood pressure(mmHg) in the morning(8am-11am), during the day(11am-5pm), and in the evening(5pm-12am), respectively?") %>
		  <li><%= f.label(:bp_1, "Morning") %>
		  <%= f.text_field(:bp_morning) %></li>
		  <li><%= f.label(:bp_2, "Noon") %>
		  <%= f.text_field(:bp_noon) %></li>
		  <li><%= f.label(:bp_3, "Night") %>
		  <%= f.text_field(:bp_night) %></li>
		
		  <%= f.label(:s8, "8. What's your SPO2 in the morning(8am-11am), during the day(11am-5pm), and in the evening(5pm-12am), respectively?(Preferred)") %>
		  <li><%= f.label(:spo2_1, "Morning") %>
		  <%= f.text_field(:spo2_morning) %></li>
		  <li><%= f.label(:spo2_2, "Noon") %>
		  <%= f.text_field(:spo2_noon) %></li>
		  <li><%= f.label(:spo2_3, "Night") %>
		  <%= f.text_field(:spo2_night) %></li>
		
			<%= f.label(:s9, "9. Please send us a video that your finger tip presses firmly on the lens with the flash on each time you test your heart rate. (Video for around 1 min) (Preferred)") %>
			<%= f.file_field("file_video")%>
	
			<%= f.label(:s10, "10. Please send us an audio file recording your breathe for around 1 min, each time you test your respiration rate. (Preferred)") %>
			<%= f.file_field("file_audio")%>
		<%= f.submit "Submit my answers", :id=>'Qsubmit' %>
		<% end %>
	</div>
</div>

app/views/outer_links/upload.html.erb
<h1>OuterLinks#upload</h1>
<p>Find me in app/views/outer_links/upload.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :s1 %><br>
    <%= f.text_field :s1 %>
  </div>
  <div class="field">
    <%= f.label :s2 %><br>
    <%= f.text_field :s2 %>
  </div>
  <div class="field">
    <%= f.label :s3 %><br>
    <%= f.text_field :s3 %>
  </div>
  <div class="field">
    <%= f.label :s4a %><br>
    <%= f.text_field :s4a %>
  </div>
  <div class="field">
    <%= f.label :s4b %><br>
    <%= f.text_field :s4b %>
  </div>
  <div class="field">
    <%= f.label :s4c %><br>
    <%= f.text_field :s4c %>
  </div>
  <div class="field">
    <%= f.label :s5a %><br>
    <%= f.text_field :s5a %>
  </div>
  <div class="field">
    <%= f.label :s5b %><br>
    <%= f.text_field :s5b %>
  </div>
  <div class="field">
    <%= f.label :s5c %><br>
    <%= f.text_field :s5c %>
  </div>
  <div class="field">
    <%= f.label :s6a %><br>
    <%= f.text_field :s6a %>
  </div>
  <div class="field">
    <%= f.label :s6b %><br>
    <%= f.text_field :s6b %>
  </div>
  <div class="field">
    <%= f.label :s6c %><br>
    <%= f.text_field :s6c %>
  </div>
  <div class="field">
    <%= f.label :s7a %><br>
    <%= f.text_field :s7a %>
  </div>
  <div class="field">
    <%= f.label :s7b %><br>
    <%= f.text_field :s7b %>
  </div>
  <div class="field">
    <%= f.label :s7c %><br>
    <%= f.text_field :s7c %>
  </div>
  <div class="field">
    <%= f.label :s8a %><br>
    <%= f.text_field :s8a %>
  </div>
  <div class="field">
    <%= f.label :s8b %><br>
    <%= f.text_field :s8b %>
  </div>
  <div class="field">
    <%= f.label :s8c %><br>
    <%= f.text_field :s8c %>
  </div>
  <div class="field">
    <%= f.label :s9 %><br>
    <%= f.text_field :s9 %>
  </div>
  <div class="field">
    <%= f.label :s10 %><br>
    <%= f.text_field :s10 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Uid</th>
      <th>S1</th>
      <th>S2</th>
      <th>S3</th>
      <th>S4a</th>
      <th>S4b</th>
      <th>S4c</th>
      <th>S5a</th>
      <th>S5b</th>
      <th>S5c</th>
      <th>S6a</th>
      <th>S6b</th>
      <th>S6c</th>
      <th>S7a</th>
      <th>S7b</th>
      <th>S7c</th>
      <th>S8a</th>
      <th>S8b</th>
      <th>S8c</th>
      <th>S9</th>
      <th>S10</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.uid %></td>
        <td><%= user.s1 %></td>
        <td><%= user.s2 %></td>
        <td><%= user.s3 %></td>
        <td><%= user.s4a %></td>
        <td><%= user.s4b %></td>
        <td><%= user.s4c %></td>
        <td><%= user.s5a %></td>
        <td><%= user.s5b %></td>
        <td><%= user.s5c %></td>
        <td><%= user.s6a %></td>
        <td><%= user.s6b %></td>
        <td><%= user.s6c %></td>
        <td><%= user.s7a %></td>
        <td><%= user.s7b %></td>
        <td><%= user.s7c %></td>
        <td><%= user.s8a %></td>
        <td><%= user.s8b %></td>
        <td><%= user.s8c %></td>
        <td><%= user.s9 %></td>
        <td><%= user.s10 %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uid:</strong>
  <%= @user.uid %>
</p>

<p>
  <strong>S1:</strong>
  <%= @user.s1 %>
</p>

<p>
  <strong>S2:</strong>
  <%= @user.s2 %>
</p>

<p>
  <strong>S3:</strong>
  <%= @user.s3 %>
</p>

<p>
  <strong>S4a:</strong>
  <%= @user.s4a %>
</p>

<p>
  <strong>S4b:</strong>
  <%= @user.s4b %>
</p>

<p>
  <strong>S4c:</strong>
  <%= @user.s4c %>
</p>

<p>
  <strong>S5a:</strong>
  <%= @user.s5a %>
</p>

<p>
  <strong>S5b:</strong>
  <%= @user.s5b %>
</p>

<p>
  <strong>S5c:</strong>
  <%= @user.s5c %>
</p>

<p>
  <strong>S6a:</strong>
  <%= @user.s6a %>
</p>

<p>
  <strong>S6b:</strong>
  <%= @user.s6b %>
</p>

<p>
  <strong>S6c:</strong>
  <%= @user.s6c %>
</p>

<p>
  <strong>S7a:</strong>
  <%= @user.s7a %>
</p>

<p>
  <strong>S7b:</strong>
  <%= @user.s7b %>
</p>

<p>
  <strong>S7c:</strong>
  <%= @user.s7c %>
</p>

<p>
  <strong>S8a:</strong>
  <%= @user.s8a %>
</p>

<p>
  <strong>S8b:</strong>
  <%= @user.s8b %>
</p>

<p>
  <strong>S8c:</strong>
  <%= @user.s8c %>
</p>

<p>
  <strong>S9:</strong>
  <%= @user.s9 %>
</p>

<p>
  <strong>S10:</strong>
  <%= @user.s10 %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>